development:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      hosts:
        - 127.0.0.1:27017
      database: dishgo          


production:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      hosts:
        - 10.128.224.88:27017
        - 10.128.221.33:27017
        - 10.128.222.208:27017
      database: dishgo        
      username: phil
      password: 0ud1Vi7u
      options:
        ssl: true
        read: :primary_preferred
 

