development:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      hosts:
        - 127.0.0.1:27017
      database: dishgo_dev          


production:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      hosts:
        - database1.dishgo.io:27017
        - database2.dishgo.io:27017
        - database3.dishgo.io:27017
      database: dishgo        
      username: phil
      password: 0ud1Vi7u
      options:
        ssl: true
        read: :primary_preferred      
